<?php

$collection = $block->getCollection();
$sortedCollection = $block->clickSortHandler($collection);

if ($sortedCollection->count()) {
?>
    <form method="post">
        <input class="sortButton" type="submit" name="ASC" class="button" value="Sort Ascending" />
        <input class="sortButton" type="submit" name="DESC" class="button" value="Sort Descending" />
    </form>
    <div>
        <div id="element">
            <?php foreach ($sortedCollection as $item) : ?>
                <?php $question = $item->getQuestion(); ?>
                <?php $answer = $item->getAnswer(); ?>

                <div data-role="collapsible">
                    <div class="question" data-role="trigger">
                        <?php echo $question ?>
                    </div>
                </div>
                <div class="answer" data-role="content"><?php echo $answer ?></div>
            <?php endforeach; ?>
        </div>
    </div>
    <script>
        require([
            'jquery',
            'accordion'
        ], function($) {
            $("#element").accordion();
        });
    </script>
<?php
}
?>